### PR TITLE
Add CI workflow for linting artifacts

### LINKED ISSUE #2: Lint shell script using shellcheck
We should validate that the shell script does not have any shellcheck findings.

### PR DESCRIPTION
**Pull request by sophokles73**
Run ShellCheck on workspace files.

This addresses #2

Closes #2

### CODE REVIEW

**Comment by sophokles73** [comment]
@kaklakariada Which ShellCheck Action can we use?

**Comment by kaklakariada** [comment]
I would prefer not to use an action. Shellcheck is already installed, please create a small script that executes it and call it from a workflow. This way it's easy to run the same check locally.

If you prefer I can take over this task, no problem!

**Comment by sophokles73** [comment]
@kaklakariada I have replaced the Action with running shellscript directly ...

**Review by kaklakariada — APPROVED** [review]

**Comment by kaklakariada** [comment]
Thanks a lot!

**Pull request merged**
